### ISSUE TITLE
Exception when toggling rnvimr in neovim

### ISSUE THREAD

**Issue by MTomczynski** [kevinhwang91/rnvimr#34]
I can't use rnvimr on my MacOS with neovim, here's the stacktrace I'm getting in the window ranger is suppose to be displayed
```
Error while loading plugin 'host'
Error while loading plugin 'service'
ranger version: ranger 1.9.3
Python version: 2.7.16 (default, Feb 29 2020, 01:55:37) [GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103
.0.29.20) (-macos10.15-objc-
Locale: None.None

Traceback (most recent call last):
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/core/main.py", line 172, in main
    ranger.api.hook_init(fm)
  File "/Users/maciek/.config/nvim/autoload/plugged/rnvimr/ranger/plugins/hacks.py", line 377, in <lambda>
    ranger.api.hook_init = lambda fm: Hacks(fm, OLD_HOOK_INIT).hook_init()
  File "/Users/maciek/.config/nvim/autoload/plugged/rnvimr/ranger/plugins/hacks.py", line 44, in hook_init
    self.draw_border()
  File "/Users/maciek/.config/nvim/autoload/plugged/rnvimr/ranger/plugins/hacks.py", line 354, in draw_bord
er
    attr_dict = client.nvim.vars['rnvimr_border_attr']
  File "/Users/maciek/Library/Python/2.7/lib/python/site-packages/pynvim/api/common.py", line 88, in __geti
tem__
    return self._get(key)
  File "/Users/maciek/Library/Python/2.7/lib/python/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/Users/maciek/Library/Python/2.7/lib/python/site-packages/pynvim/msgpack_rpc/session.py", line 102,
 in request
    raise self.error_wrapper(err)
NvimError: Key not found: rnvimr_border_attr

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues

[Process exited 1]
```

Healthcheck info:
health#rnvimr#check
```
  - ERROR: Failed to run healthcheck for "rnvimr" plugin. Exception:
    function health#check[21]..health#rnvimr#check[5]..<SNR>137_check_rpc, line 34
    Vim(call):E900: Invalid channel id
```

![image](https://user-images.githubusercontent.com/15198021/85167246-d0581d80-b268-11ea-880f-f1939f9c8dfd.png)

**Comment by kevinhwang91** [comment]
> Requirements
Ranger (v1.9.3 at least)
Pynvim
Neovim
Python3.6
Ueberzug (optional, if you don't use Tmux, Ueberzug is required at least d86eeb)

>Q: I'm Using Mac, this plugin doesn't work for me.

A: Install Requirements first, you should install Ranger by pip3 install ranger-fm instead of brew install ranger because the Ranger installed by brew still using Python2.

**Comment by MTomczynski** [comment]
Thanks! Ranger from pip is not working for me but I guess that's another problem 😅 
```
Traceback (most recent call last):
  File "/usr/local/bin/ranger", line 36, in <module>
    import ranger  # NOQA pylint: disable=import-self,wrong-import-position
ModuleNotFoundError: No module named 'ranger'
```

**Comment by kevinhwang91** [comment]
Uninstall Ranger installed by brew first. My Mac env works fine with rnvimr. Good luck!
